gemfile: Gemfile

concurrency: '1'

PrePush:
  CustomScript:
    enabled: true
    command: ["swift test"]

PreCommit:
  BundleCheck:
    enabled: true

  CustomScript:
    enabled: true
    command: ["./bin/pre-commit.sh"]