language: objective-c
osx_image: xcode11
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 8

script:
- set -o pipefail
- swift --version
- rake
- bundle exec fastlane pass_tests
- bundle exec danger
