language: objective-c
osx_image: xcode11
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 8
before_install:
- openssl aes-256-cbc -K $encrypted_5ce6572667b1_key -iv $encrypted_5ce6572667b1_iv -in cookies.txt.enc -out cookies.txt -d
script:
- set -o pipefail
- swift --version
- rake
- brew install thii/unxip/unxip
- wget --load-cookies=cookies.txt -c https://download.developer.apple.com/Developer_Tools/Xcode_11_Beta_4/Xcode_11_Beta_4.xip
- unxip Xcode_11_Beta_4.xip /Applications/Xcode-beta.app
- xcode-select -s /Applications/Xcode-beta.app/Contents/Developer
- xcode-select --install
- xcodebuild -scheme MiniSwift-Package -enableCodeCoverage YES test
- curl -s https://codecov.io/bash | bash -s -- -F ios -J 'Mini'
- bundle exec danger

