language: swift
osx_image: xcode11

cache:
  bundler: true
  cocoapods: true

addons:
  homebrew:
    brewfile: true

script:
- set -o pipefail
- swift --version
- rake
- rake test
- bundle exec fastlane pass_tests
- bundle exec fastlane tests
- bundle exec pod repo update
- bundle exec pod lib lint --allow-warnings --fail-fast
- bundle exec danger