language: swift
script:
- set -o pipefail
- swift --version
- xcodebuild clean build test -project Mini.xcodeproj -scheme Mini -destination "platform=iOS Simulator,name=iPhone 7" | xcpretty -f `xcpretty-travis-formatter`
- swiftlint lint
- pod lib lint
