language: objective-c
osx_image: xcode11
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 8

script:
- set -o pipefail
- swift --version
- rake
- xcodebuild -scheme MiniSwift-Package -enableCodeCoverage YES test
- curl -s https://codecov.io/bash | bash -s -- -F ios -J 'Mini'
- bundle exec danger
